// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: anki_vector/messaging/settings.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Anki.Vector.ExternalInterface {

  /// <summary>Holder for reflection information generated from anki_vector/messaging/settings.proto</summary>
  public static partial class SettingsReflection {

    #region Descriptor
    /// <summary>File descriptor for anki_vector/messaging/settings.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SettingsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRhbmtpX3ZlY3Rvci9tZXNzYWdpbmcvc2V0dGluZ3MucHJvdG8SHkFua2ku",
            "VmVjdG9yLmV4dGVybmFsX2ludGVyZmFjZSolCgpBcGlWZXJzaW9uEgsKB0lO",
            "VkFMSUQQABIKCgZMQVRFU1QQASpSCgZWb2x1bWUSCAoETVVURRAAEgcKA0xP",
            "VxABEg4KCk1FRElVTV9MT1cQAhIKCgZNRURJVU0QAxIPCgtNRURJVU1fSElH",
            "SBAEEggKBEhJR0gQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Anki.Vector.ExternalInterface.ApiVersion), typeof(global::Anki.Vector.ExternalInterface.Volume), }, null));
    }
    #endregion

  }
  #region Enums
  public enum ApiVersion {
    [pbr::OriginalName("INVALID")] Invalid = 0,
    [pbr::OriginalName("LATEST")] Latest = 1,
  }

  public enum Volume {
    [pbr::OriginalName("MUTE")] Mute = 0,
    [pbr::OriginalName("LOW")] Low = 1,
    [pbr::OriginalName("MEDIUM_LOW")] MediumLow = 2,
    [pbr::OriginalName("MEDIUM")] Medium = 3,
    [pbr::OriginalName("MEDIUM_HIGH")] MediumHigh = 4,
    [pbr::OriginalName("HIGH")] High = 5,
  }

  #endregion

}

#endregion Designer generated code
